-   id: rails_best_practices
    name: rails_best_practices
    entry: rails_best_practices
    language: ruby
    'types': [ruby]
    args: ["."]
    require_serial: false
    additional_dependencies: []
